# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smokerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='sensordata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='smokerapi.SensorData'),
        ),
    ]
